export const ProductService = {
    getProducts: () => [
        {
            // name: "Sneaker A",
            image: "https://via.placeholder.com/150",
            category: "Sneakers",
            price: "$199.99",
            status: true,
            rating: 4,
            inventoryStatus: 'STOCK DISPONIVEL',
        },
        {
            // name: "Sneaker B",
            image: "https://via.placeholder.com/150",
            category: "Sneakers",
            price: "$179.99",
            status: true,
            rating: 3,
            inventoryStatus: 'BAIXO STOCK',
        },
        {
            // name: "Running Shoes",
            image: "https://via.placeholder.com/150",
            category: "Running",
            price: "$129.99",
            status: true,
            rating: 5,
            inventoryStatus: 'STOCK DISPONIVEL',
        },
        {
            // name: "Casual Shoes",
            image: "https://via.placeholder.com/150",
            category: "Casual",
            price: "$89.99",
            status: true,
            rating: 4,
            inventoryStatus: 'BAIXO STOCK',
        },
        {
            // name: "Hiking Boots",
            image: "https://via.placeholder.com/150",
            category: "Outdoor",
            price: "$149.99",
            status: true,
            rating: 4.5,
            inventoryStatus: 'STOCK DISPONIVEL',
        },
    ],
};
